[package]
name = "simulator"
version = "0.25.1"
edition.workspace = true
default-run = "simulator"

[dependencies]
anyhow.workspace = true
eframe = { version = "0.29.0", features = [
    "wgpu",
    "glow",
    "default_fonts",
    "persistence",
    "puffin",
] }
egui = { version = "0.29.0", features = ["rayon", "log"] }
egui_plot = "0.29.0"
egui_extras = { version = "0.29.0", features = ["svg"] }
ecolor = "0.29.0"
cgal = { workspace = true, features = ["serde"] }
cpd = { path = "../cpd", features = ["serde", "gpu"] }
cpd-wgpu = { path = "../cpd-wgpu" }
pollster = "0.3.0"
nalgebra = { workspace = true, features = ["serde-serialize"] }
serde.workspace = true
rayon.workspace = true
strum.workspace = true
strum_macros.workspace = true
enum-map = { workspace = true, features = ["serde"] }
paste.workspace = true
typed-builder.workspace = true
derive-getters.workspace = true
directories = "5.0.1"
rfd = "0.14.1"
lazy_static = "1.4.0"
indexmap = { version = "2.2.6", features = ["serde"] }
pathdiff = "0.2.1"
csv = "1.3.0"
sealed.workspace = true
fxhash.workspace = true
nalgebra-ext = { workspace = true, features = ["serde"] }
pot = "3.0.0"
envy = "0.4.2"
pretty_env_logger = "0.5.0"
log = "0.4"
function = { workspace = true, features = ["serde"] }
puffin.workspace = true
puffin_http = "0.16.0"
const_format = { version = "0.2.32", features = [
    "rust_1_64",
    "const_generics"
] }
uuid = { version = "1.8.0", features = ["fast-rng", "v4", "serde"] }
mesh = { workspace = true, features = ["serde"] }



[package.metadata.packager]
name = "DPM-Simulator"
product-name = "DPM Simulator"
identifier = "com.dpm.simulator"
version = "0.25.1"
authors = ["DPM Team"]
description = "Continuum Interaction Particle Dynamics Simulator"
homepage = "https://github.com/dpm-simulator/dpm"
icons = ["src/assets/simulator-icon.svg"]
formats = ["deb"]

[package.metadata.packager.linux]

[package.metadata.packager.deb]
section = "science"
depends = [
    "libgtk-3-0",
    "libasound2",
    "libc6",
    "libgcc-s1",
    "libstdc++6",
    "libgmp10",
    "libmpfr6",
    "libcgal13 | libcgal11",
    "libboost-system-dev"
]

[dev-dependencies]
test-case.workspace = true
